# windows is currently unsupport at invent.kde.org. Will be activated when ready
include:
 - https://invent.kde.org/sysadmin/ci-utilities/-/raw/master/gitlab-templates/linux.yml
 - https://invent.kde.org/sysadmin/ci-utilities/-/raw/master/gitlab-templates/freebsd.yml

Options:
    cppcheck-arguments: '--enable=warning,style,performance -ibuild -itest -suppressions-list=CppCheckSuppressions.txt'
